# Generated by Django 5.2.3 on 2025-07-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0002_paciente_created_paciente_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estatus',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1),
        ),
    ]
