# Generated by Django 5.2.3 on 2025-07-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0004_antescedentesmedicos_consulta_diagnostico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antescedentesmedicos',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='diagnostico',
            old_name='id_consulta',
            new_name='conuslta',
        ),
        migrations.RenameField(
            model_name='imagenesclinicas',
            old_name='id_consulta',
            new_name='consulta',
        ),
        migrations.RenameField(
            model_name='imagenesclinicas',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='tratamiento',
            old_name='id_consulta',
            new_name='consulta',
        ),
    ]
