# Generated by Django 5.2.3 on 2025-07-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0005_rename_id_paciente_antescedentesmedicos_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='consulta',
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tratamiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Diagnostico',
        ),
        migrations.DeleteModel(
            name='Tratamiento',
        ),
    ]
