# Generated by Django 5.2.3 on 2025-08-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0006_remove_tratamiento_consulta_consulta_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenesclinicas',
            name='resultados',
            field=models.ImageField(blank=True, null=True, upload_to='resultados/'),
        ),
    ]
