# Generated by Django 5.2.3 on 2025-09-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0007_imagenesclinicas_resultados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antescedentesmedicos',
            options={'ordering': ['-created'], 'verbose_name': 'Antecedente Medico', 'verbose_name_plural': 'Antecedentes Medicos'},
        ),
        migrations.RenameField(
            model_name='antescedentesmedicos',
            old_name='paciente',
            new_name='id_paciente',
        ),
        migrations.RemoveField(
            model_name='antescedentesmedicos',
            name='diabetes',
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='alergia_especifica',
            field=models.BooleanField(default=False, verbose_name='Alergia específica'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='alergia_medicamentos',
            field=models.BooleanField(default=False, verbose_name='Alergia a algún medicamento'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='anemia',
            field=models.BooleanField(default=False, verbose_name='Anemia'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='chupar_dedo',
            field=models.BooleanField(default=False, verbose_name='Chupar dedo o labios'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='consumo_citricos',
            field=models.BooleanField(default=False, verbose_name='Consumo frecuente de cítricos'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='desgaste',
            field=models.BooleanField(default=False, verbose_name='Desgaste - Abrasion'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='discapacidad',
            field=models.BooleanField(default=False, verbose_name='Discapacidad'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='embarazo',
            field=models.BooleanField(default=False, verbose_name='Embarazo/Sospecha de embarazo'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='epilepsias',
            field=models.BooleanField(default=False, verbose_name='Epilepsia/Convulsiones'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='fuma',
            field=models.BooleanField(default=False, verbose_name='¿Fuma?'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='gastritis',
            field=models.BooleanField(default=False, verbose_name='Gastritis/Úlceras'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='morder_unas',
            field=models.BooleanField(default=False, verbose_name='Morderse las uñas'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='mordida_abierta',
            field=models.BooleanField(default=False, verbose_name='Mordida abierta'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='mordida_cruzada',
            field=models.BooleanField(default=False, verbose_name='Mordida cruzada'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='problemas_atm',
            field=models.BooleanField(default=False, verbose_name='Problemas ATM chasquidos'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='problemas_cardiacos',
            field=models.BooleanField(default=False, verbose_name='¿Tiene problemas cardíacos?'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='problemas_coagulacion',
            field=models.BooleanField(default=False, verbose_name='¿Tiene problemas de coagulación?'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='rechinar_dientes',
            field=models.BooleanField(default=False, verbose_name='Rechinar los dientes'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='respiracion_bucal',
            field=models.BooleanField(default=False, verbose_name='Respiración bucal'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='sangrado_encias',
            field=models.BooleanField(default=False, verbose_name='Sangrado de encías'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='sobremorida_horizontal',
            field=models.BooleanField(default=False, verbose_name='Sobremordida horizontal'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='sobremorida_vertical',
            field=models.BooleanField(default=False, verbose_name='Sobremordida vertical'),
        ),
        migrations.AddField(
            model_name='antescedentesmedicos',
            name='tratamiento_medico',
            field=models.BooleanField(default=False, verbose_name='¿Está en tratamiento médico?'),
        ),
        migrations.AlterField(
            model_name='antescedentesmedicos',
            name='hipertension',
            field=models.BooleanField(default=False, verbose_name='Hipertensión'),
        ),
    ]
