# Generated by Django 5.2.3 on 2025-09-24 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0008_alter_antescedentesmedicos_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antescedentesmedicos',
            old_name='epilepsias',
            new_name='epilepsia',
        ),
        migrations.RenameField(
            model_name='antescedentesmedicos',
            old_name='sobremorida_horizontal',
            new_name='sobremordida_horizontal',
        ),
        migrations.RenameField(
            model_name='antescedentesmedicos',
            old_name='sobremorida_vertical',
            new_name='sobremordida_vertical',
        ),
    ]
