# Generated by Django 5.2.3 on 2025-09-26 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0009_rename_epilepsias_antescedentesmedicos_epilepsia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dientes_permanentes', models.JSONField(default=dict)),
                ('dientes_deciduos', models.JSONField(default=dict)),
                ('resumen_clunico', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paceinte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas', to='Pacientes.paciente')),
            ],
        ),
    ]
