# Generated by Django 5.2.3 on 2025-09-26 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0010_odontograma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odontograma',
            old_name='paceinte',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='odontograma',
            old_name='resumen_clunico',
            new_name='resumen_clinico',
        ),
    ]
