# Generated by Django 5.2.7 on 2025-11-08 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0012_paciente_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioComparativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('diagnostico', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('antes_oclusal_superior', models.ImageField(upload_to='estudios/antes/')),
                ('antes_lateral_izquierda', models.ImageField(upload_to='estudios/antes/')),
                ('antes_frontal', models.ImageField(upload_to='estudios/antes/')),
                ('antes_lateral_derecha', models.ImageField(upload_to='estudios/antes/')),
                ('antes_oclusal_inferior', models.ImageField(upload_to='estudios/antes/')),
                ('despues_perfil', models.ImageField(blank=True, null=True, upload_to='estudios/despues/')),
                ('despues_semiperfil', models.ImageField(blank=True, null=True, upload_to='estudios/despues/')),
                ('despues_retrato_frontal', models.ImageField(blank=True, null=True, upload_to='estudios/despues/')),
                ('despues_retrato_sonrisa', models.ImageField(blank=True, null=True, upload_to='estudios/despues/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios_comparativos', to='Pacientes.paciente')),
            ],
        ),
    ]
