# Generated by Django 5.2.7 on 2025-11-08 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0013_estudiocomparativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiocomparativo',
            options={'verbose_name': 'Estudio Comparativo', 'verbose_name_plural': 'Estudios Comparativos'},
        ),
        migrations.RenameField(
            model_name='estudiocomparativo',
            old_name='updated',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='estudiocomparativo',
            old_name='created',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='estudiocomparativo',
            name='antes_frontal',
            field=models.ImageField(blank=True, null=True, upload_to='estudios/antes/'),
        ),
        migrations.AlterField(
            model_name='estudiocomparativo',
            name='antes_lateral_derecha',
            field=models.ImageField(blank=True, null=True, upload_to='estudios/antes/'),
        ),
        migrations.AlterField(
            model_name='estudiocomparativo',
            name='antes_lateral_izquierda',
            field=models.ImageField(blank=True, null=True, upload_to='estudios/antes/'),
        ),
        migrations.AlterField(
            model_name='estudiocomparativo',
            name='antes_oclusal_inferior',
            field=models.ImageField(blank=True, null=True, upload_to='estudios/antes/'),
        ),
        migrations.AlterField(
            model_name='estudiocomparativo',
            name='antes_oclusal_superior',
            field=models.ImageField(blank=True, null=True, upload_to='estudios/antes/'),
        ),
        migrations.AlterField(
            model_name='estudiocomparativo',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.paciente'),
        ),
    ]
