# Generated by Django 5.2.7 on 2025-11-10 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0014_alter_estudiocomparativo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_aceptacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_ine', models.FileField(blank=True, null=True, upload_to='consentimientos/ine/')),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='consentimientos/pdf/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.paciente')),
            ],
        ),
    ]
