# Generated by Django 5.2.7 on 2025-11-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0015_consentimiento'),
    ]

    operations = [
    ]
