# Generated by Django 5.2.7 on 2025-11-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0016_auto_20251123_0010'),
        ('Pacientes', '0016_rename_id_paciente_antescedentesmedicos_paciente_and_more'),
    ]

    operations = [
    ]
