# Generated by Django 5.2.7 on 2025-11-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0020_alter_paciente_email_alter_paciente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentimiento',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
