# Generated by Django 5.2.7 on 2025-11-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='clinica_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Clínica'),
        ),
    ]
